# name: Terraform Workflow
# on: 
#   pull_request:
#     branches: [ main ]
# jobs:
#   plan:
#     name: Terraform init
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with: 
#           terraform_version: ${{env.TF_VERSION}}
#       - name: Terraform check
#         run: terraform fmt -check -recursive
#       - name: Terraform Init
#         run: terraform 
         


